 const service = [
  { key: "airControl", value: "空调" },
  { key: "animalCries", value: "动物叫" },
  { key: "app", value: "应用" },
  { key: "calc", value: "计算" },
  { key: "carCare", value: "车服务" },
  { key: "cmd", value: "命令" },
  { key: "constellation", value: "星座" },
  { key: "datetime", value: "时间" },
  //{ key: "flight", value: "航班" },
  { key: "haidilao", value: "海底捞" },
  { key: "help", value: "帮助" },
  { key: "idiom", value: "成语" },
  { key: "idiomGame", value: "成语接龙游戏" },
  { key: "musicGame", value: "音乐游戏" },
  { key: "motorViolation", value: "违章查询" },
  { key: "mediaControl", value: "媒体控制" },
  { key: "story", value: "故事"},
  //{ key: "mapU", value: "导航" },
  //{ key: "internetRadio", value: "节目" },
  { key: "news", value: "新闻" },
  { key: "personalName", value: "重命名" },
  { key: "poetry", value: "诗词" },
  { key: "poetryGame", value: "对诗游戏" },
  { key: "weixin", value: "微信" },
  { key: "message", value: "短信" },
  { key: "viewCmd", value: "可见即可说" },
  { key: "warmTips", value: "主动提醒" },
  { key: "vehicleInfo", value: "车辆信息" },
  { key: "video", value: "视频" },
  //{ key: "train", value: "火车" },
  { key: "smartHome", value: "智能家居" },
  //{ key: "telephone", value: "电话" },
  { key: "scheduleX", value: "日程安排" },
  { key: "sceneInsurance", value: "场景险" },
  { key: "preResearch", value: "预言" },
  { key: "radio", value: "电台" },
  //{ key: "musicX", value: "音乐" },
  { key: "cityOfPro", value: "国内城市查询" },
  { key: "carControl", value: "车身控制" },
  { key: "carWash", value: "洗车" },
  { key: "carNumber", value: "限行尾号查询" },
  { key: "lottery", value: "彩票" },
  { key: "relationShip", value: "家族关系神器" },
  { key: "chineseZodiac", value: "生肖运势" },
  { key: "canlendar", value: "万年历" },
  { key: "holiday", value: "假期安排" },
  { key: "duoidiomSolita", value: "成语接龙" },
  { key: "Riddle", value: "谜语" },
  { key: "college", value: "高校查询" },
  { key: "cookbook", value: "菜谱" },
  { key: "wordsMeaning", value: "词语解释" },
  { key: "parkingLot", value: "停车场" },
  { key: "gasStation", value: "加油站" },
  { key: "FamilyName", value: "百家姓" },
  { key: "captalInfo", value: "首都查询" },
  { key: "queryCapital", value: "省会查询" },
  { key: "garbageClassif", value: "垃圾分类" },
  { key: "volumeScaler", value: "体积换算" },
  { key: "powerScaler", value: "功率换算" },
  { key: "weather", value:"天气"},
  { key: "areaScaler", value: "面积换算" },
  { key: "numberScaler", value: "进制换算" },
  { key: "weightScaler", value: "重量换算" },
  { key: "temperature", value: "温度换算" },
  { key: "dream", value: "周公解梦" },
  { key: "translation", value: "翻译" },
  { key: "wordFinding", value: "同反义词" },
  { key: "sentenceMaking", value: "造句" },
  { key: "petrolPrice", value: "今日油价" },
  { key: "joke", value: "笑话" },
  { key: "brainTeaser", value: "脑筋急转弯" },
  { key: "stroke", value: "写字笔画" },
  { key: "historyToday", value: "历史上的今天" },
  { key: "forex", value: "汇率查询与货币" },
  { key: "chat", value:"聊天" },
  { key: "changba", value: "唱吧" },
  { key: "stock", value: "股票" },
  { key: "all_smartHome", value: "智能家居" },
  { key: "poetry", value: "诗词" },
  { key: "warmTips", value:"温馨提示" },
  { key: "orderFood", value: "点餐" },
  { key: "datetimeX", value: "日期" },
  { key: "coupletGame", value: "对联游戏" },
  { key: "baike", value: "百科" },
  { key: "AIchannel", value:"AI频道" },
  { key: "playControl", value:"播放控制" },
  { key: "feedback", value: "反馈" },
  { key: "scenicSpots", value: "二次交互" },
  { key: "oilprice", value: "油价" },
  { key: "ppersonalChat", value: "角色问答" },
  { key: "photoView", value:"查看图片" },

];

export default service